### ISSUE TITLE
Improper display of certain characters

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/planet#1]
Recently, there was a blog [post by Manish](https://medium.com/@manishbisht/google-summer-of-code-17-with-phpmyadmin-d0e32c6a343c?source=rss-ed17b81d6783------2) with the title `Google Summer of Code’ 17 with phpmyadmin` -- this appeared as `Google Summer of Codeâ€™ 17 with phpmyadmin` 

Photo:
![image](https://cloud.githubusercontent.com/assets/1443710/26164507/d5345276-3afa-11e7-850a-6365b7437722.png)

Deven had [a post](https://devenbansod.wordpress.com/2017/05/14/project-details-gsoc-2017-with-phpmyadmin/) with some strange characters as well, such as "Â  Â  Â  2.Â Issue #31 : Provide email notification for new reports" which looks like a normal heading on his blog and `â€˜Clear all notificationsâ€™` which should be `‘Clear all notifications’` 

Photo:
![image](https://cloud.githubusercontent.com/assets/1443710/26164525/e267a65a-3afa-11e7-897c-76384ba121ca.png)

So on the surface it looks like there is a problem with:
* U+2018 : LEFT SINGLE QUOTATION MARK {single turned comma quotation mark}
* U+2019 : RIGHT SINGLE QUOTATION MARK {single comma quotation mark}

However, I also see that ’ (RIGHT SINGLE QUOTATION MARK) is correctly rendered in the body of Manish's post, so I'm a bit less certain about what's going on here.

Photo: 
![image](https://cloud.githubusercontent.com/assets/1443710/26164571/079a2cb8-3afb-11e7-8215-d28646f20dec.png)

**Comment by nijel** [comment]
Confirmed even with caches removed, needs deeper look.

**Comment by nijel** [comment]
Should be fixed now.
