### ISSUE TITLE
Mixed content in planet.phpmyadmin.net

### ISSUE THREAD

**Issue by emanuelb** [phpmyadmin/planet#5]
Visit:
https://planet.phpmyadmin.net/
Result: (mixed content, message from browser console)
Mixed Content: The page at 'https://planet.phpmyadmin.net/' was loaded over HTTPS, but requested an insecure image 'http://feeds.wordpress.com/1.0/comments/devenbansod.wordpress.com/433/'. This content should also be served over HTTPS.

**Comment by williamdes** [comment]
Seems to be fixed now
